### ISSUE TITLE
When playing as country and building a firm the game crashes

### ISSUE THREAD

**Issue by lassefolkersen** [lassefolkersen/highfrontier#22]
The error message is pretty clear. The source is [here](https://github.com/lassefolkersen/highfrontier/blob/fa0566e664e31a01755ad6c45f9f3f650d64872d/gui.py#L3147). And it happens because max_size is smaller than start_value. The only question I can't figure out is why is it like that? Seems to only happen when I select to start as a country, never as a company 
```
228 - value: b'PrintIM\x000250\x00\x00\x02\x00\x02\x00\x01\x00\x00\x00\x01\x01\x00\x00\x00\x00'
225357
3184
basic food production
Traceback (most recent call last):
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 451, in <module>
    introGui = IntroGui()
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 81, in __init__
    self.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 105, in receive_click
    button.activate(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui_components.py", line 499, in activate
    return_value = self.function(self.label, self.function_parameter)
  File "/Users/lassefolkersen/Documents/highfrontier/intro.py", line 444, in start_new_game
    self.main.start_loop(companyName = cn,
  File "/Users/lassefolkersen/Documents/highfrontier/main.py", line 114, in start_loop
    gui_instance.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 113, in receive_click
    return_value = self.active_window.receive_click(event)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 2814, in receive_click
    self.commodity_size_selection(self.fast_list.selected_name)
  File "/Users/lassefolkersen/Documents/highfrontier/gui.py", line 3147, in commodity_size_selection
    raise Exception("This has been observed before. See printout")
Exception: This has been observed before. See printout
```

**Comment by JonathanLochridge** [comment]
Interesting, I hadn't gotten that far yet. Although I wanted to try playing as a country today as well.
I can try to verify to see if this reproduces on linux.

Based on the context, I think those may be GUI values?

That when you specified the commodity size, the info was incorrectly recorded, or it was an invalid size?

This is based on the existing size of a building, 
Or if a new building based on the technology and population.

If the population is too low, or the number of technologies in a certain list too high then the maximum might end up under the minimum.

It should already be filtering out cases, and preventing the size from being smaller than 1.

**Comment by lassefolkersen** [comment]
Yeah, I can't really tell either. In this fix I just enforce the value to be smaller. As I understood it happens in the edge case where a country starts up a firm that's really really big (because it can apprently), and then you want to build a firm of the same type and the gui goes haywire because the value is too big to show.

**Comment by JonathanLochridge** [comment]
Huh, I thought it was when you are the country? good to know though.
I want to be sure when I go to test it.

But you think the PR resolves both issues?

**Comment by lassefolkersen** [comment]
Yeah I think so. They are pretty small changes, maybe I should make a more general 'bug hunting' PR. But let's just get them in, there's little chance they'll mess up things.
